@startuml

[*] --> State1 : starting

State1 -> State2 : renderNewBoard
State1: new Game

State2 -> State3 : checkmate
State2: Playing

State3: GameOver

State2 --> [*] : quitWhilePlaying
State3 --> [*] : showScore
@enduml